### ISSUE TITLE
Decompression type only support 7z? Doesn't support zip, etc.?

### ISSUE THREAD

**Issue by neomissing** [pedrolcl/libq7zip#6]
Decompression type only support 7z? Doesn't support zip, etc.?I test zip and other types are not supported.

**Comment by pedrolcl** [comment]
Yes, that is correct. This library supports only the 7z format. If you want to process several other compression formats in your program you can include more libraries.

The zip format is implemented on several libraries, for instance [minizip](https://www.winimage.com/zLibDll/minizip.html), and there is also a convenient [Qt wrapper](https://github.com/stachenov/quazip) on top of it.

**Comment by pedrolcl** [comment]
If you really need to support multiple compression formats in your Qt application, better take a look to [QArchive](https://github.com/antony-jr/QArchive)
